# Generated by Django 3.1.2 on 2020-11-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201113_2040'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetooneroom',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_rooms_as_user1', to='content.profile', verbose_name='Собеседник 1'),
        ),
        migrations.AlterField(
            model_name='onetooneroom',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_rooms_as_user2', to='content.profile', verbose_name='Собеседник 2'),
        ),
    ]
