# Generated by Django 3.1.2 on 2020-11-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, verbose_name='Пол')),
                ('about', models.TextField(max_length=1000, verbose_name='О пользователе')),
                ('vk_id', models.IntegerField(verbose_name='Идентификатор пользователя во вконтакте')),
                ('inst_id', models.IntegerField(verbose_name='Идентификатор пользователя в инстаграме')),
                ('interests', models.ManyToManyField(related_name='profiles', to='content.Interest', verbose_name='Интересы')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('image', models.ImageField(upload_to='events', verbose_name='Изображение')),
                ('tags', models.ManyToManyField(related_name='events', to='content.Interest', verbose_name='С какими интересами связано')),
            ],
        ),
    ]
