# Generated by Django 3.1.2 on 2020-11-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата проведения')),
                ('image', models.ImageField(upload_to='events', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True, verbose_name='Пол')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, verbose_name='О пользователе')),
                ('vk_id', models.IntegerField(null=True, verbose_name='Идентификатор пользователя во вконтакте')),
                ('inst_id', models.IntegerField(null=True, verbose_name='Идентификатор пользователя в инстаграме')),
                ('interests', models.ManyToManyField(related_name='profiles', to='content.Interest', verbose_name='Интересы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False, verbose_name='Уже посещено')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='content.event', verbose_name='Событие')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='content.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='going_to_participate',
            field=models.ManyToManyField(related_name='going_to_participate', through='content.Intent', to='content.Profile', verbose_name='Собираются учавствовать'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='content.Interest', verbose_name='Связанные интересы'),
        ),
    ]
