# Generated by Django 3.1.2 on 2020-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='looking_for_a_company',
            field=models.ManyToManyField(related_name='looking_for_a_company_to', to='content.Profile', verbose_name='Ищут компанию'),
        ),
    ]
