# Generated by Django 3.1.2 on 2020-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201102_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О пользователе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inst_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор пользователя в инстаграме'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор пользователя во вконтакте'),
        ),
    ]
