# Generated by Django 3.1.2 on 2020-12-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201123_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vk_id',
            new_name='vk_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inst_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
