# Generated by Django 3.1.2 on 2020-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20201207_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_id',
            field=models.PositiveIntegerField(blank=True, help_text='Необходимо выставить вручную, если выставляется через админку', null=True, verbose_name='id пользователя во вконтакте'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Male'), ('Женщина', 'Female'), ('Другое', 'Other')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль пользователя во вконтакте'),
        ),
    ]
