# Generated by Django 3.1.2 on 2020-12-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20201211_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата проведения'),
        ),
    ]
