# Generated by Django 3.1.2 on 2020-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20201211_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения'),
        ),
    ]
