# Generated by Django 3.1.2 on 2020-12-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20201211_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='content.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='content.profile', verbose_name='Профиль'),
        ),
    ]
