# Generated by Django 3.1.2 on 2020-12-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20201220_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='О пользователе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Другое'), ('N', 'Не указан')], default='N', max_length=2, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ссылка на профиль пользователя во вконтакте'),
        ),
    ]
