# Generated by Django 3.1.2 on 2020-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20201220_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое'), ('N', 'Не указан')], default='N', max_length=2, null=True, verbose_name='Пол'),
        ),
    ]
